### ISSUE TITLE
Implicit conversion of TITLETRANSLIT to int instead of string

### ISSUE THREAD

**Issue by RhythmLunatic** [piulin/pegjs-ssc-parser#1]
It's probably not super important, but the parser is turning tags like "15E5" into 1500000. I checked by setting a breakpoint at https://piulin.github.io/piured/piured-engine/js/Song/Song.js line 219.

**Comment by piulin** [comment]
Right, that is because there is not an actual distincion of types for each entry in the parser. I guess TITLETRANSLIT is supposed to be only string only, but if a number (even in scientific notation) is written it will be casted as a number type. (https://github.com/piulin/pegjs-ssc-parser/blob/main/grammar/SSC.pegjs line 86)
